pub mod add_rarities_to_bank;
pub mod add_to_bank_whitelist;
pub mod authorize_funder;
pub mod cancel_reward;
pub mod cancel_reward_alpha;
pub mod claim;
pub mod claim_alpha;
pub mod deauthorize_funder;
pub mod flash_deposit;
pub mod flash_deposit_alpha;
pub mod fund_reward;
pub mod fund_reward_alpha;
pub mod init_farm_alpha;
pub mod init_fixed_farm;
pub mod init_probable_farm;
pub mod init_farmer_alpha;
pub mod init_fixed_farmer;
pub mod init_probable_farmer;
pub mod lock_reward;
pub mod refresh_farmer;
pub mod refresh_farmer_signed;
pub mod refresh_farmer_signed_alpha;
pub mod refresh_farmer_alpha;
pub mod remove_from_bank_whitelist;
pub mod stake;
pub mod stake_alpha;
pub mod treasury_payout;
pub mod unstake;
pub mod unstake_alpha;
pub mod update_farm;
pub mod alpha_tokenswap;

pub use add_rarities_to_bank::*;
pub use add_to_bank_whitelist::*;
pub use authorize_funder::*;
pub use cancel_reward::*;
pub use cancel_reward_alpha::*;
pub use claim::*;
pub use claim_alpha::*;
pub use deauthorize_funder::*;
pub use flash_deposit::*;
pub use flash_deposit_alpha::*;
pub use fund_reward::*;
pub use fund_reward_alpha::*;
pub use init_farm_alpha::*;
pub use init_fixed_farm::*;
pub use init_probable_farm::*;
pub use init_farmer_alpha::*;
pub use init_fixed_farmer::*;
pub use init_probable_farmer::*;
pub use lock_reward::*;
pub use refresh_farmer::*;
pub use refresh_farmer_alpha::*;
pub use refresh_farmer_signed::*;
pub use refresh_farmer_signed_alpha::*;
pub use remove_from_bank_whitelist::*;
pub use stake::*;
pub use stake_alpha::*;
pub use treasury_payout::*;
pub use unstake::*;
pub use unstake_alpha::*;
pub use update_farm::*;
pub use alpha_tokenswap::*;
// have to duplicate or this won't show up in IDL

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug, Default, PartialEq)]
pub struct RarityConfig {
    pub mint: Pubkey,
    pub rarity_points: u16,
}
