[features]
seeds = false
[programs.devnet]
gem_bank = "F4SDKmdyr6pzESeRuew4CkWj2qpTZ1xbn6o7Bvsa9297"
magic_stake = "CMftun186ypSsjsZM8eVfDA7AsPZLoScWpTEYBvCzZVQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/Users/bhargavveepuri/dev-solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
