[features]
seeds = false
[programs.devnet]
gem_bank = "A3uMghFkMxJasxd7JDiTAZwBCMZhyhtxiZxxWY6pNpMK"
magic_stake = "ETiwBTiVf2wNApe5Qc1sGozV3nkUDKNRVuCWzJSFWWfV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/Users/bhargavveepuri/wallets/solana/solana-wallet_linux/TnC98o4aMW7bcXcZXEsFaTBGJy5KPscd1jfL7WuRf6x.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
