[features]
seeds = false
[programs.mainnet]
token_swap = "2PrbTwpNBDNDrZQBWtxmGcuSnxZzRxE1ECfL9EEMVxkG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/Users/bhargavveepuri/wallets/solana/solana-wallet_linux/ryaNsMVq6FaS4oYT6gXxKsPEzGqryWmMb2PQKABsSRX.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
